---

- name: "Blockinfile to edit files"
  gather_facts: true
  hosts: all
  remote_user: lex
  #become: true
  vars:
    packages:
      - mysql-server
      - phpmyadmin
  tasks:
    - name: "Install packages old style with explicit list"
      remote_user: lex
      apt:
        name: "{{ item }}"
      with_items:
        - mysql-server
        - phpmyadmin
    - name: "Install packages old style using varibles"
      remote_user: lex
      apt:
        name: "{{ item }}"
      with_items:
        - "{{ packages }}"
    - name: "Install packages with explicit list"
      remote_user: lex
      apt:
        name: ['mysql-server', 'phpmyadmin']
    - name: "Install packages new style using varibles"
      remote_user: lex
      apt:
        name: "{{ packages }}"
  
    

