---

- name: Run file commands
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Create a directory
      file:
        path: /home/lex/myfolder
        state: directory
        owner: lex
        group: lex

    - name: Delete ejemplo file
      file:
        path: /home/lex/ ejemplo.bak
        state: absent