# Check
- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 1.0 Check if Vault SSH Helper is already installed
  stat:
    path:  /etc/vault-ssh-helper.d
  register: vault_ssh_already_installed

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 1.1 Verify the configuration  Vault SSH Helper
  command: /usr/local/bin/vault-ssh-helper -verify-only  -config /etc/vault-ssh-helper.d/config.hcl
  ignore_errors: true
  when:
    - vault_ssh_already_installed.stat.exists
  register: verify_config_vault_ssh
  

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 1.2 Print configuration status  Vault SSH Helper
  debug:
    msg: The configuration  Vault SSH Helper is Ok
  when:
    - verify_config_vault_ssh is succeeded 
    - vault_ssh_already_installed.stat.exists

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 1.3 Print configuration status Vault SSH Helper
  debug:
    msg: Vault SSH Helper is not configured yet  {{verify_config_vault_ssh.msg}}
  when:
    - verify_config_vault_ssh.msg is defined and (verify_config_vault_ssh.msg is defined and verify_config_vault_ssh.msg.find('[Errno 2]') != -1)
    - vault_ssh_already_installed.stat.exists
  
- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 1.4 Print configuration status Vault SSH Helper
  debug:
    msg: Vault SSH Helper is not installed
  when:
  - not vault_ssh_already_installed.stat.exists

#BLOCK UNZIP
- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 2.0 Check if Unzip is install
  stat:
    path: /usr/bin/unzip
  register: unzip_status
  when:
    - not vault_ssh_already_installed.stat.exists #when vault not isntalled

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 2.0.1 Print Unzip is install
  debug:
    msg: Unzip is installed
  when:
    - not vault_ssh_already_installed.stat.exists
    - unzip_status.stat.exists

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 2.0.2 Check if Unzip rpm  is in remote path /tmp
  stat:
    path: /tmp/unzip-6.0-5.el6.x86_64.rpm
  register: unzip_rpm_status
  when:
    - not vault_ssh_already_installed.stat.exists

# Copy Unzip in remote path
- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 2.1 Copy Unzip rpm package in remote path /tmp
  copy:
    src: ./packages/unzip/centos/unzip-6.0-5.el6.x86_64.rpm
    dest: /tmp/
    mode: '0755'
  when: 
    - (not vault_ssh_already_installed.stat.exists) and ( not unzip_status.stat.exists) and (not unzip_rpm_status.stat.exists)

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 2.2 Install Unzip in remote host
  # yum:
  #   name: /tmp/unzip-6.0-5.el6.x86_64.rpm
  #   state: present
  command: rpm -ivh /tmp/unzip-6.0-5.el6.x86_64.rpm
  #disable_gpg_check: true
  when:
    - not vault_ssh_already_installed.stat.exists
    - not unzip_status.stat.exists

#BLOCK VAULT SSH
- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 3.0 Check if  Vault SSH Helper.zip is in remote host
  stat:
    path: /tmp/vault-ssh-helper_0.2.0_linux_amd64.zip
  register: vault_zip_status
  when:
    - not vault_ssh_already_installed.stat.exists

#Copy vault_ssh_helper in remote path
- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 3.1 Copy Vault SSH Helper.zip a file in remote path /tmp
  copy:
    src: ./packages/vault_ssh/ubuntu/vault-ssh-helper_0.2.0_linux_amd64.zip
    dest: /tmp/
    mode: '0755'
  when: 
    - not vault_ssh_already_installed.stat.exists and not vault_zip_status.stat.exists

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 3.2 Install Vault SSH Helper.zip in remote path /usr/local/bin
  unarchive:
    src: /tmp/vault-ssh-helper_0.2.0_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
  register: vault_ssh_installed
  when:
    - not vault_ssh_already_installed.stat.exists
    - not vault_zip_status.stat.exists

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 4.0 Create directory (/etc/vault-ssh-helper.d) to store the configuration file
  file: 
    path: /etc/vault-ssh-helper.d/ 
    mode: '0755' 
    state: directory
  when:
    - vault_ssh_installed.changed

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 4.1 Create file config.hcl in remote path  /etc/vault-ssh-helper.d/
  file: 
    path: /etc/vault-ssh-helper.d/config.hcl
    mode: '0755' 
    state: touch
  when:
    - vault_ssh_installed.changed

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 4.2 Edit file config.hcl
  lineinfile: 
    dest: /etc/vault-ssh-helper.d/config.hcl
    line: '{{ item }}'
  with_items:
    - 'vault_addr = "{{vault_addr}}"'
    - 'tls_skip_verify = {{tls_skip_verify}}'
    - 'ssh_mount_point = "{{ssh_mount_point}}"' 
    - 'allowed_roles = "{{allowed_roles}}"'
    - 'allowed_cidr_list = "{{allowed_cidr_list}}"'
  when:
    - vault_ssh_installed.changed  or (verify_config_vault_ssh.msg is defined and verify_config_vault_ssh.msg.find('[Errno 2]') != -1)

#BLOCK PAM sshd configuration
- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 5.0.0 Check if directory /etc/pam.d/sshd.orig exists
  stat:
    path:  /etc/pam.d/sshd.orig
  register: vault_sshd_orig
  when:
    - vault_ssh_installed.changed  or (verify_config_vault_ssh.msg is defined and verify_config_vault_ssh.msg.find('[Errno 2]') != -1)

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 5.0 BLOCKthe original configuration file /etc/pam.d/sshd
  command: cp /etc/pam.d/sshd /etc/pam.d/sshd.orig
  when:
    - vault_sshd_orig.stat is defined and not vault_sshd_orig.stat.exists
    - vault_ssh_installed.changed or (verify_config_vault_ssh.msg is defined and verify_config_vault_ssh.msg.find('[Errno 2]') != -1)

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 5.2 Commented out the standard Unix authentication /etc/pam.d/sshd
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: '{{ item }}'
    #insertafter: '#%PAM*'
    line:  '#{{ item }}' 
  with_items:
    - 'auth       substack     password-auth'
    - 'password   include      password-auth'
  when:
    - vault_ssh_installed.changed or (verify_config_vault_ssh.msg is defined and verify_config_vault_ssh.msg.find('[Errno 2]') != -1)

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 5.3 Replaced with authentication through vault-ssh-helper /etc/pam.d/sshd
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sshd
    #regexp: '#%PAM-1.0_'
    insertafter: 'auth       include      postlogin'
    line: '{{ item }}'
  with_items:
    - 'auth       optional       pam_unix.so not_set_pass use_first_pass nodelay'
    - 'auth       requisite      pam_exec.so quiet expose_authtok log=/var/log/vault-ssh.log /usr/local/bin/vault-ssh-helper -config=/etc/vault-ssh-helper.d/config.hcl'
    
  when:
    - vault_ssh_installed.changed or (verify_config_vault_ssh.msg is defined and verify_config_vault_ssh.msg.find('[Errno 2]') != -1)

#BLOCK PAM: sshd configuration
- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 6.0 Check if directory /etc/ssh/sshd_config.orig exists
  stat:
    path:  /etc/ssh/sshd_config.orig
  register: vault_sshd_config_orig
  when:
    - vault_ssh_installed.changed  or (verify_config_vault_ssh.msg is defined and verify_config_vault_ssh.msg.find('[Errno 2]') != -1)

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 6.1 Copy the original configuration file /etc/ssh/sshd_config
  command: cp /etc/ssh/sshd_config /etc/ssh/sshd_config.orig
  when:
    - vault_sshd_config_orig.stat is defined and not vault_sshd_config_orig.stat.exists
    - vault_ssh_installed.changed or (verify_config_vault_ssh.msg is defined and verify_config_vault_ssh.msg.find('[Errno 2]') != -1)
    
- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 6.2 Modify (comment) the sshd configuration file /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{ item }}'
    line:  '#{{ item }}' 
  with_items:
    - 'ChallengeResponseAuthentication no'
    - 'UsePAM no'
    - 'PasswordAuthentication yes'
  when:
    - vault_ssh_installed.changed or (verify_config_vault_ssh.msg is defined and verify_config_vault_ssh.msg.find('[Errno 2]') != -1)

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 6.3 Modify (uncomment) the sshd configuration file /etc/ssh/sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '#{{ item }}'
    line: '{{ item }}'
  with_items:
    - 'ChallengeResponseAuthentication yes'
    - 'UsePAM yes'
    - 'PasswordAuthentication no'
  when:
    - vault_ssh_installed.changed or (verify_config_vault_ssh.msg is defined and verify_config_vault_ssh.msg.find('[Errno 2]') != -1)

#BLOCK CERTS
- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 7.0 check if the certificate exists in remote host /etc/ssl/certs/
  stat:
    path: /etc/ssl/certs/vault_portal.crt
  register: vault_certs_status
  when:
    - vault_ssh_installed.changed or (verify_config_vault_ssh.msg is defined and verify_config_vault_ssh.msg.find('[Errno 2]') != -1)

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 7 .1 Copy certificate in remote path /etc/ssl/certs/
  copy:
    src: ./packages/certificate/vault_portal.crt
    dest: /etc/ssl/certs/
    mode: '0755'
  when: 
    - vault_certs_status.stat is defined and not vault_certs_status.stat.exists

#RESTART SSHD
- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 8.0 Restart the sshd service.
  service:
    name: sshd
    state: restarted
  when: 
    - vault_ssh_installed.changed or (verify_config_vault_ssh.msg is defined and verify_config_vault_ssh.msg.find('[Errno 2]') != -1)

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 8.1 Verify the configuration  Vault SSH Helper
  command: /usr/local/bin/vault-ssh-helper -verify-only  -config /etc/vault-ssh-helper.d/config.hcl
  ignore_errors: true
  when:
    - vault_ssh_installed.changed or (verify_config_vault_ssh.msg is defined and verify_config_vault_ssh.msg.find('[Errno 2]') != -1)
  register: verify_config_vault_ssh
  
- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 8.2 Print configuration status  Vault SSH Helper
  debug:
    msg: The configuration  Vault SSH Helper is Ok
  when:
    - vault_ssh_installed.changed and verify_config_vault_ssh is succeeded 

#============================================================================#
#                           Selinux configuration                            #
#============================================================================#

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 0.0 SELINUX
  command: getenforce
  register: status_selinux
  when:
    - vault_ssh_installed.changed 
    - verify_config_vault_ssh is succeeded

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 0.1 Selinux status
  debug:
    msg: Selinux is status_selinux.stdout
  when:
    - vault_ssh_installed.changed
    - status_selinux is defined and status_selinux is succeeded 

# - name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 0.2 Copy module in remote host
#   copy:
#     src: ./packages/module/centos/Centos7.pp
#     dest: /tmp/
#     mode: '0755'
#   when: 
#     - vault_ssh_installed.changed
#     - status_selinux is defined and status_selinux.stdout == "Enforcing"
    

# - name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | 0.3 Install module whith Semodule
#   command: semodule -i /tmp/Centos7.pp
#   when: 
#     - vault_ssh_installed.changed
#     - status_selinux is defined and status_selinux.stdout == "Enforcing"
    
#============================================================================#
#             Remove and uninstall packages of remote HOST                   #
#============================================================================#

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | Rv.0 Check if Unzip deb package exists in temporary file
  stat:
    path: /tmp/unzip-6.0-5.el6.x86_64.rpm
  register: unzip_stat
  when:
  - not vault_ssh_already_installed.stat.exists

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | Rv.1 Delete Unzip deb package of temporary file
  file:
    path: /tmp/unzip-6.0-5.el6.x86_64.rpm
    state: absent
  when: unzip_stat.stat is defined and unzip_stat.stat.exists

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | Rv.2 Check if Unzip is installed
  stat:
    path: /usr/bin/unzip
  register: unzip_status
  when:
  - not vault_ssh_already_installed.stat.exists

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | Rv.3 Uninstall Unzip 
  yum:
    name:  unzip
    state: absent
  when:
    -  unzip_status.stat is defined and unzip_status.stat.exists

#remove vault ssh package
- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | Rv.4 Check if Vault SSH Helper zip package exists in temporary file
  stat:
    path: /tmp/vault-ssh-helper_0.2.0_linux_amd64.zip
  register: vault_ssh_stat
  when:
  - not vault_ssh_already_installed.stat.exists

- name: Vault SSH Helper | {{ansible_distribution}} {{ansible_distribution_major_version}} | Rv.5 Delete Vault SSH Helper zip package of temporary file
  file:
    path: /tmp/vault-ssh-helper_0.2.0_linux_amd64.zip
    state: absent
  when:  vault_ssh_stat.stat is defined and vault_ssh_stat.stat.exists

#===============================#
#          ROLLBACK             #
#===============================#